network: mainnet
auto_execute: false

risk:
  max_account_risk_pct: 10.0    # % of SOL balance
  base_stop_pct: 20.0           # default stop %
  base_target_pct: 40.0         # default take profit %
  partial_tp_at_2x_pct: 50.0    # sell 50% at 2x

filters:
  min_liquidity_usd: 20000
  min_fdv_usd: 300000
  max_pair_age_hours: 72
  min_txns_last_hour: 200
  bubblemaps_top10_max_pct: 20.0

execution:
  # Fixed slippage and priority fee
  slippage_bps: 150                    # 1.50%
  priority_fee_micro_lamports: 1000    # 1000 µ-lamports/CU
  compute_unit_limit: 1_000_000

wallet:
  key_name: SOL_PRIVATE_KEY

strategy:
  ma_window: 20
  atr_window: 14
  rr_floor: 2.0

preferred_input_mints:
  - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v   # USDC
  - So11111111111111111111111111111111111111112   # WSOL
